version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    ports:
      - "5005:8080"

  poll-service:
    build:
      context: .
      dockerfile: src/PollService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Chuỗi_Kết_Nối_Neon_DB_Của_Bạn

  vote-service:
    build:
      context: .
      dockerfile: src/VoteService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Chuỗi_Kết_Nối_Neon_DB_Của_Bạn

  realtime-service:
    build:
      context: .
      dockerfile: src/RealtimeService/Dockerfile
    ports:
      - "5003:8080"
