name: Run Build Check

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend/PollBuilder.API/PollBuilder.API-master

    - name: Build backend
      run: dotnet build --no-restore
      working-directory: ./backend/PollBuilder.API/PollBuilder.API-master